name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read rust-toolchain file
        id: rust-toolchain
        run: echo "toolchain=$(cat rust-toolchain)" >> $GITHUB_OUTPUT

      - name: Add rustfmt
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.rust-toolchain.outputs.toolchain }}
          components: clippy, rustfmt
      - uses: Swatinem/rust-cache@v2

      - name: Fmt
        run: cargo fmt --all -- --check
      - name: Check
        run: cargo check --release --all-features --all-targets --workspace --verbose
      - name: Clippy
        run: cargo clippy --release --all-features --all-targets --workspace --verbose -- -D warnings
      - name: Run tests
        run: cargo test --all-features --all-targets --verbose
